project:
  type: website
  output-dir: docs

lang: nb

website:
  title: "NSM27"
  favicon: images/nsm27.png
  page-footer:
    center: |
      ![Norsk statistisk forening](images/nsf_logo.png){height=80px}

      Kontaktperson: Bård Støve – [bard.stove@uib.no](mailto:bard.stove@uib.no)
  navbar:
    title: false
    logo: images/nsm27.png
    left:
      - href: index.qmd
        text: "Hjem"
      - program.qmd
      - praktisk_info.qmd
      - forkurs.qmd
      - paamelding.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
